x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes: 
      - ./etc/loki/:/etc/loki/
      - loki:/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - grafana:/var/lib/grafana
    depends_on:
      - loki
    logging: *default-logging

volumes:
  grafana:
  loki: